$defs:
  transactions_config:
    description: TransactionsConfig holds configuration for transactions.
    type: object
    properties:
      enabled:
        type: boolean
    additionalProperties: false
type: object
properties:
  transactions:
    $ref: transactions_config
additionalProperties: false
